services:

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache-httpd
    depends_on:
      - php
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../public/:/var/www/html #Alterado para ser igual à estrutura no container PHP

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        LOCAL_UID: ${UID:-1000}
        LOCAL_GID: ${GID:-1000}
    container_name: php-fpm
    networks:
      - database
      - web
    volumes:
      - ../../:/var/www/html

  mysql:
    container_name: mysql-db
    image: mysql:8.4
    user: "${UID:-1000}:${GID:-1000}"
    networks:
      - database
    volumes:
      - ${HOME}/database:/var/lib/mysql
      - ../blog_app_SCHEMA.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../blog_app_DATA.sql:/docker-entrypoint-initdb.d/02-data.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: blog_app      # Create initial database
      MYSQL_USER: blogApp         # Create application user
      MYSQL_PASSWORD: ${DB_PASSWORD}     # Application user password

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    networks:
      - database
      - web
    environment:
      PMA_HOST: mysql-db  # Tell phpMyAdmin where MySQL is
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: https://blog-app.com/phpmyadmin/

networks:
    database:
      driver: bridge
      name: blogapp_database
    web:
      driver: bridge
      name: blogapp_web