#Regras de Compressão
<IfModule mod_deflate.c>
    #Compressão de arquivos baseados em texto
    #Por enquanto, apenas html, css e js (dado o contexto do trabalho)
    AddOutputFilterByType DEFLATE text/html text/css text/javascript

    #Nível da compressão em 5, para ficar num meio termo.
    DeflateCompressionLevel 5
</IfModule>

<VirtualHost *:80>
    ServerName blog-app.com
    ServerAlias www.blog-app.com localhost
    #Alterado para ser igual à estrutura no container PHP
    DocumentRoot /var/www/html/public

    Protocols http/1.1
    
    <Directory "/var/www/html/public">
        AllowOverride All
        Require all granted
        Options FollowSymLinks

        #Substi o ProxyPassMatch, assim a existência
        # dos arquivos são validados ANTES.
        <FilesMatch \.php$>
            SetHandler "proxy:fcgi://php:9000"
        </FilesMatch>
    </Directory>

    #Substituído por SetHandler no FilesMatch
    #ProxyPassMatch ^/(?!phpmyadmin/)(.*\.php)$ fcgi://php:9000/var/www/html/public/$1

    ProxyPass /phpmyadmin/ http://phpmyadmin:80/
    ProxyPassReverse /phpmyadmin/ http://phpmyadmin:80/
          
    DirectoryIndex index.php

    #Redirect permanent / https://blog-app.com/
    
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>

<VirtualHost *:443>
    ServerName blog-app.com
    ServerAlias www.blog-app.com localhost  
    #Alterado para ser igual à estrutura no container PHP
    DocumentRoot /var/www/html/public

    Protocols h2 http/1.1

    #Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains"
    
    <Directory "/var/www/html/public">
        AllowOverride All
        Require all granted
        Options FollowSymLinks

        #Substi o ProxyPassMatch, assim a existência
        # dos arquivos são validados ANTES.
        <FilesMatch \.php$>
            SetHandler "proxy:fcgi://php:9000"
        </FilesMatch>
    </Directory>

    # Enable SSL Engine and point to certificate files
    SSLEngine on
    SSLCertificateFile "/usr/local/apache2/conf/certs/apache-selfsigned.crt"
    SSLCertificateKeyFile "/usr/local/apache2/conf/certs/apache-selfsigned.key"

    #Substituído por SetHandler no FilesMatch
    #ProxyPassMatch ^/(?!phpmyadmin/)(.*\.php)$ fcgi://php:9000/var/www/html/public/$1

    ProxyPass /phpmyadmin/ http://phpmyadmin:80/
    ProxyPassReverse /phpmyadmin/ http://phpmyadmin:80/

    Redirect permanent /phpmyadmin /phpmyadmin/

    DirectoryIndex index.php
    
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>